server:
  port: 9001
spring:
#  profiles:
#    active: test
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      username: vendor
      password: Dspread01
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://172.16.10.247/vendor_db?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&useSSL=false
#      url: jdbc:mysql://localhost/vendor_db?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&useSSL=false
#      driver-class-name: com.mysql.jdbc.Driver
#      url: jdbc:mysql://10.66.37.196:3306/jxhc?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false
#      username: jxhc
#      password: ncepri
      #password: ncepri@2021
      initial-size: 10
      max-active: 100
      min-idle: 10
      max-wait: 60000
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      #Oracle需要打开注释
      #validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        #login-username: admin
        #login-password: admin
      filter:
        stat:
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: false
        wall:
          config:
            multi-statement-allow: true
  redis:
    open: true  # 是否开启redis缓存  true开启   false关闭
    database: 0
    host: 127.0.0.1
    port: 6379
    password:   # 密码（默认为空）
    timeout: 6000ms  # 连接超时时长（毫秒）
    jedis:
      pool:
        max-active: 1000  # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1ms      # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 10      # 连接池中的最大空闲连接
        min-idle: 5

#  jackson:
#    date-format: yyyy-MM-dd HH:mm:ss
#    time-zone: GMT+8


#mybatis
mybatis-plus:
  mapper-locations: classpath:/mappers/**/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  type-aliases-package:  com.dps.tms.bean
  global-config:
    #数据库相关配置
    db-config:
      #主键类型  AUTO:"数据库ID自增", INPUT:"用户输入ID", ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID";
      id-type: AUTO
      #字段策略 IGNORED:"忽略判断",NOT_NULL:"非 NULL 判断"),NOT_EMPTY:"非空判断"
      field-strategy: NOT_NULL
      #驼峰下划线转换
      column-underline: true
      logic-delete-value: -1
      logic-not-delete-value: 0
    banner: false
  #原生配置
  configuration:
    map-underscore-to-camel-case: false
    cache-enabled: false
    call-setters-on-nulls: true
    jdbc-type-for-null: 'null'

logging:
  level:
    com.dps.tms.mapper.* : debug


##多数据源的配置
#dynamic:
#  datasource:
#    oracleSso:
#      driver-class-name: oracle.jdbc.OracleDriver
#      url: jdbc:oracle:thin:@10.66.36.106:1521:ORCL
#      username: scglpt
#      password: scglpt
#      validationQuery:  SELECT 1 FROM DUAL


ca:
  config:
    path: D:\ssl_k\java
    root_path: root
    root_alias: dspreadRoot
    server_path: mis
    client_path: cli
    default_pw: dspreadpwd
    key_store_suffix: p12
    host: 172.16.10.220
    port: 1818
#    root_id: 0001


